# This file is only used to generate documentation, the configuration items are not complete，
# allowable<https://github.com/wu-kan/wu-kan.github.io/blob/master/_config.yml>Get complete configuration documents and examples！
title: Guner's Backyard # Site title
description: A content-first, sliding sidebar theme for Jekyll. # Information behind the avatar，<br/>Represents newline
url: https://jekyll-theme-WuK.wu-kan.cn
baseurl: "" # If your blog is built in a certain directory, please add the name of the directory here, and in all the links configured below`/assets`Also add before, that is`/your_baseurl/assets`。Don’t end this item'/'。

defaults: # Use all configuration options<https://jekyllrb.com/docs/configuration/front-matter-defaults/>Function configuration
  - scope:
      path: "" # an empty string here means all files in the project
    values: # The following configuration items can also be customized on any page
      jekyll-theme-WuK: # The custom styles of my theme are all in this namespace
        default:
          body:
            theme-base: theme-base-07 # Optional theme colors include08~0f，see <https://github.com/poole/lanyon>
            layout-reverse: false # After opening /sidebar/ on the right，On the left
            sidebar-overlay: false # Text does not follow after opening /sidebar/ Move and move
          append_to_head: # Inline html To introduce and customize plugins，Make sure you know what you are doing before deleting。The way to customize the plugin can refer to this article </_posts/2019-01-18-基于Jekyll搭建个人博客/>
            - | #Some on-page optimization tags，If you don't understand, you can skip
              <meta
                name="viewport"
                content="width=device-width, initial-scale=1.0, maximum-scale=1"
              />
              <meta
                http-equiv="content-type"
                content="text/html; charset=utf-8"
              />
              <link
                rel="alternate"
                href="/feed.xml"
                title="RSS"
                type="application/rss+xml"
              />
            - | # Website icon，Can be replaced with your own picture，change href Part of
              <link
                rel="apple-touch-icon-precomposed"
                href="https://gravatar.loli.net/avatar/289efba375d63424de3c49569c446744?s=320"
              />
              <link
                rel="shortcut
                icon"
                href="https://gravatar.loli.net/avatar/289efba375d63424de3c49569c446744?s=32"
              />
            - | # From lanyon Page style，Don't change
              <link
                rel="stylesheet"
                href="https://cdn.jsdelivr.net/combine/gh/poole/lanyon@v1.1.0/public/css/poole.min.css,gh/poole/lanyon@v1.1.0/public/css/lanyon.min.css"
              />
            - | # Introduce fontawesome Icon style
              <link
                rel="stylesheet"
                href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css"
              />
            - | # Introduce live2d Signboard girl！You don’t need to delete this item
              <link
                rel="stylesheet"
                href="https://cdn.jsdelivr.net/gh/Dreamer-Paul/Pio@2.4/static/pio.min.css"
              />
              <script
                async="async"
                src="https://cdn.jsdelivr.net/combine/gh/Dreamer-Paul/Pio@2.4/static/l2d.min.js,gh/Dreamer-Paul/Pio@2.4/static/pio.min.js"
                onload='
                  if (screen.width > screen.height)
                  {
                    let pio_container = document.createElement("div");
                    pio_container.classList.add("pio-container");
                    pio_container.classList.add("right");
                    pio_container.style.bottom = "-2rem";
                    pio_container.style.zIndex = "1";
                    document.body.insertAdjacentElement("beforeend", pio_container);
                    let pio_action = document.createElement("div");
                    pio_action.classList.add("pio-action");
                    pio_container.insertAdjacentElement("beforeend", pio_action);
                    let pio_canvas = document.createElement("canvas");
                    pio_canvas.id = "pio";
                    pio_canvas.style.width = "14rem";
                    pio_canvas.width = "600";
                    pio_canvas.height = "800";
                    pio_container.insertAdjacentElement("beforeend", pio_canvas);
                    let pio = new Paul_Pio({
                      "mode": "fixed",
                      "hidden": true,
                      "night": "for(let i=7; i<16; ++i) if(document.body.classList.contains(`theme-base-0`+i.toString(16))) { document.body.classList.remove(`theme-base-0`+i.toString(16)); document.body.classList.add(`theme-base-0`+((i-6)%9+7).toString(16)); break; }",
                      "content": {
                        "link": ["https://wu-kan.cn"],
                        "skin": ["You want to replace it with my friend?？", "Let her take a vacation~"],
                        "custom": [{
                          "selector": "a",
                          "type": "link",
                        }, {
                          "selector": ".sidebar-toggle",
                          "text": "Open the sidebar~"
                        }, {
                          "selector": ".effect-info",
                          "text": "Wow，what have you found！"
                        }, {
                          "selector": "#sidebar-search-input",
                          "text": "What do you want to search for？A lot of dry goods！"
                        }, {
                          "selector": "#toc",
                          "text": "This is the directory~"
                        }, {
                          "selector": ".page-title",
                          "text": "This is the title~"
                        }, {
                          "selector": ".v",
                          "text": "Comment not reviewed，Be responsible for your speech~"
                        }]
                      },
                      "model": [
                        "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/33/model.2018.bls-winter.json",
                        "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/platelet-2/model.json",
                        "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/xiaomai/xiaomai.model.json",
                        "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/mashiro/seifuku.model.json",
                        "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/seele/model.json",
                        "https:\/\/cdn.jsdelivr.net/gh/imuncle/live2d/model/Violet/14.json",
                        "https:\/\/cdn.jsdelivr.net/gh/xiaoski/live2d_models_collection/Kobayaxi/Kobayaxi.model.json",
                        "https:\/\/cdn.jsdelivr.net/gh/xiaoski/live2d_models_collection/mikoto/mikoto.model.json",
                        "https:\/\/cdn.jsdelivr.net/gh/xiaoski/live2d_models_collection/uiharu/uiharu.model.json"]
                    });
                  }'
              ></script>
            - | # Baidu crawler push，http Site usage http://push.zhanzhang.baidu.com/push.js
              <script
                src='https://zz.bdstatic.com/linksubmit/push.js'
                defer="defer"
              ></script>
            - | # Website background image，Split vertical screen、宽屏；Widescreen，If you don't want to use it, you can delete all of this item；If you want to change the wallpaper image, you can change the part in the url to your own，For example, you put /assets/image/background.jpg，Then change to url(/assets/image/background.jpg)
              <style>
                .wrap {
                  min-height: 100vh;
                  display: inline-block;
                  background-size: 100vw auto;
                  background-position: center top;
                  background-repeat: no-repeat;
                  background-attachment: fixed;
                  background-image: url(https://Mizuno-Ai.wu-kan.cn/pixiv/74559485_p1.webp);
                }
                @media (min-aspect-ratio: 2400/1850) {
                  .wrap {
                    background-image: url(https://Mizuno-Ai.wu-kan.cn/pixiv/71932901_p0.webp);
                  }
                }
              </style>
            - | # Website font
              <style>
                html,
                h1,
                h2,
                h3,
                h4,
                h5,
                h6,
                .sidebar {
                  font-family: Menlo, Monaco, "Courier New", Microsoft JhengHei, monospace;
                }
              </style>
            - | # Fix the problem of clicking the sidebar button to return to the top
              <style>
                .sidebar-checkbox {
                  display: none;
                }
                .sidebar-toggle {
                  position: fixed;
                }
              </style>
            - | # Fix the default style of inline pictures
              <style>
                img {
                  display: inline-block;
                  margin: 0;
                }
              </style>
            - | # Sidebar avatar effect
              <style>
                .effect {
                  margin: 1rem;
                  perspective: 900px;
                }
                .effect-info {
                  text-align: center;
                  backface-visibility: hidden;
                  position: absolute;
                  top: 0;
                  transform-style: preserve-3d;
                }
                .effect-img {
                  z-index: 11;
                  width: 100%;
                  height: 100%;
                  position: relative;
                  transition: all 0.5s ease-in-out;
                }
                .effect-img:before {
                  position: absolute;
                  display: block;
                }
                .effect-right_to_left .effect-img {
                  transform-origin: 0% 50%;
                }
                .effect-right_to_left:hover .effect-img {
                  transform: rotate3d(0, 1, 0, -180deg);
                }
              </style>
            - | # Rainbow scroll bar，Only for Chrome Valid in browser
              <style>
                ::-webkit-scrollbar {
                  width: 4px;
                  height: 4px;
                }
                ::-webkit-scrollbar-thumb {
                  background-image: linear-gradient(0deg, #00C0FF 0%, #FFCF00 50%, #FC4F4F 100%);
                }
              </style>
            - | # Select font color
              <style>
                ::selection {
                  color: #fff;
                  background: #26351c;
                }
              </style>
          sidebar: # Under this configuration item are some configurations about the sidebar
            disable: true # Does it show/not show sidebar
            wordcount: # Total station word count
              enable: false # It is recommended to close when debugging locally，Very affect the site generation speed（The time required is proportional to the square of the number of blog posts）
        home: # See configuration<https://revealjs.com/>
          append_to_section_tag:
            - key: data-markdown
            - key: data-separator # Horizontal display page separator
              value: <!-- slide -->
            - key: data-separator-vertical # Vertical display page separator
              value: <!-- slide vertical=true -->
            - key: data-background-color
              value: "White"
          prepend: |
            <link
              rel="stylesheet"
              href="https://cdn.jsdelivr.net/combine/npm/reveal.js@4.0.0/dist/reveal.min.css,npm/reveal.js@4.0.0/dist/theme/serif.min.css"
            />
            <style>
              .sidebar {
                line-height: 1.5;
              }
              .reveal .slides {
                text-align: left;
              }
              .reveal a {
                color: #268BD2;
              }
            </style>
            <script
              defer="defer"
              src="https://cdn.jsdelivr.net/combine/npm/reveal.js@4.0.0/dist/reveal.min.js,npm/reveal.js@4.0.0/plugin/markdown/markdown.js"
              onload="
              document.getElementsByClassName('wrap')[0].classList.add('reveal');
              Reveal.initialize({
                height: '100%',
                hash: true,
                mouseWheel: true,
                navigationMode: 'linear',
                plugins: [ RevealMarkdown ]
              });
            "></script>

# githubpage See the supported plugins on <https://pages.github.com/versions/>
plugins: # <https://jekyllrb.com/docs/plugins/>
  - jekyll-readme-index # use readme do index，Thereby and github Consistent rendering
  - jekyll-default-layout # For each of markdown Automatic generated layout
  - jekyll-seo-tag # Generate title for each page

readme_index:
  with_frontmatter: true

# permalink: /_posts/:year-:month-:day-:title/ # The address format of the generated article，I hope it and _posts The format under the directory is the same
# timezone: Asia/Shanghai # solve githubpage Incorrect display time，see <https://www.iana.org/time-zones>
# future: false # Do not post articles in the future

# limit_posts: 999 # Limit the number of blog posts
# encoding: utf-8

markdown: kramdown
kramdown: # see <https://kramdown.gettalong.org/options.html>
  input: GFM # see <http://jekyllcn.com/docs/configuration/#kramdown>
  syntax_highlighter_opts: # visible <https://kramdown.gettalong.org/syntax_highlighter/rouge.html>
    disable: true # Turn off the default highlight，Switch to prismjs

# The following is githubpage Unmodifiable parameters，see <https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll>
#lsi: false # Generate an index for related articles
#safe: true # Disable custom plugins
#source: [your repo's top level directory] # Jekyll Path to read file
#incremental: false # Incremental generation
#highlighter: rouge # Code highlighter
#gist:
#  noscript: false
#kramdown:
#  math_engine: mathjax
#  syntax_highlighter: rouge
